[package]
name = "rusty_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "*"
egui_extras = "*"
env_logger = "*"
rfd = "*"
anyhow = "*"
flate2 = "*"
log = "*"
tar = "*"
prost = "0.6"
# Only necessary if using Protobuf well-known types:
prost-types = "0.6"

[build-dependencies]
prost-build = { version = "0.6" }
