[package]
name = "rusty_bench"
version = "0.1.0"
edition = "2021"
description = "Rustybench is a gui tool to manage audio files an the SD-Card of a Toniebox audio player"
repository = "https://github.com/Schievel1/rustybench"
authors = ["Pascal Jaeger <pascal.jaeger@leimstift.de>"]
license = "GPL-2.0-only"

[dependencies]
eframe = "*"
egui_extras = "*"
egui-modal = "*"
env_logger = "*"
rfd = "*"
anyhow = "*"
flate2 = "*"
log = "*"
tar = "*"
prost = "0.6"
open = "*"
toniefile = { git = "https://github.com/Schievel1/toniefile" }
rubato = "0.12.0"
symphonia = { version = "0.5.3", features = ["all"] }
arrayvec = "0.7.1"
lazy_static = "1.4.0"

[build-dependencies]
prost-build = { version = "0.6" }
